POST http://yourhost:port/V3/Alexa.svc/json/Control/AdjustBrightness/
Content-Type: text/plain
Host: yourhost

{
  "directive": {
    "header": {
      "namespace": "Alexa.BrightnessController",
      "name": "AdjustBrightness",
      "payloadVersion": "3",
      "messageId": "1bd5d003-31b9-476f-ad03-71d471922820",
      "correlationToken": "dFMb0z+PgpgdDmluhJ1LddFvSqZ/jCc8ptlAKulUj90jSqg=="
    },
    "endpoint": {
      "scope": {
        "type": "BearerToken",
        "token": "your-token"
      },
      "endpointId": "9AB03900-D923-47B9-BE7F-833892A388B9",
      "cookie": {
          "path": "sys://Home/House/First/Den/TrackA"
      }
    },
    "payload": {
      "brightnessDelta": -5
    }
  }
}