POST http://yourhost:port/V3/Alexa.svc/json/Authorization/
Content-Type: application/json
Host: yourhost

{
  "directive": {
    "header": {
      "namespace": "Alexa.Authorization",
      "name": "AcceptGrant",
      "messageId": "5f8a426e-01e4-4cc9-8b79-65f8bd0fd8a4",
      "correlationToken": "dFMb0z+PgpsdfjhluhJ1LddFvSqZ/jCc8ptlAKulUj90jSqg==",
      "payloadVersion": "3"
    },
    "payload": {
      "grant": {
        "access_token": "Atza|IwEBIIVGSe9...",
        "refresh_token": "Atzr|IwEBIHLuPW...",
        "token_type": "bearer",
        "expires_in": 900
      },
      "grantee": {
        "type": "BearerToken",
        "token": "some-token",
        "localAccessToken": "your-token"
      }
    }
  }
}

