POST http://yourhost:port/V3/Alexa.svc/json/Control/SetPowerState/
Content-Type: text/plain
Host: yourhost

{
  "directive": {
    "header": {
      "namespace": "Alexa.ColorTemperatureController",
      "name": "IncreaseColorTemperature",
      "payloadVersion": "3",
      "messageId": "B12B536E-B6E7-4E38-AF18-D43BC34FA869",
      "correlationToken": "dFMb0z+PgpgdDmluhJ1LddFvSqZ/jCc8ptlAKulUj90jSqg=="
    },
    "endpoint": {
      "scope": {
        "type": "BearerToken",
        "token": "your-token"
      },
      "endpointId": "9AB03900-D923-47B9-BE7F-833892A388B9",
      "cookie": {
          "path": "sys://Home/House/First/Den/Mood"
      }
    },
    "payload": {}
  }
}
