POST http://yourhost:port/V3/Alexa.svc/json/ReportState/
Content-Type: application/json
Host: yourhost

{
  "directive": {
    "header": {
      "messageId": "abc-123-def-456",
      "correlationToken": "abcdef-123456",
      "namespace": "Alexa",
      "name": "ReportState",
      "payloadVersion": "3"
    },
    "endpoint": {
      "endpointId": "CD6AD6C0-6FA6-488A-8A37-8A32E8BF04CA",
      "cookie": {},
      "scope":{
            "type":"BearerToken",
            "token":"some-token",
            "localAccessToken": "your-token"
      }
    },
    "payload": {
    }
  }
}

