POST http://localhost:51124/V3/Alexa.svc/json/Control/SetThermostatMode/
Content-Type: application/json
Host: localhost

{
  "directive": {
    "header": {
      "namespace": "Alexa.ThermostatController",
      "name": "SetThermostatMode",
      "payloadVersion": "3",
      "messageId": "1233CC6C-EB28-4DC2-917D-5205CF9488EE",
      "correlationToken": "dFMb0z+PgpgdDmluhJ1LddFvSqZ/jCc8ptlAKulUj90jSqg=="
    },
    "endpoint": {
      "scope": {
        "type": "BearerToken",
        "token": "some-access-token",
        "localAccessToken": "premise-access-token"
      },
      "endpointId": "0EE3CC6C-EB28-4DC2-917D-5205CF9488EE",
      "cookie": {}
    },
    "payload": {
      "thermostatMode":{
        "value": "OFF"
      }
    }
  }
}


